version: '3'
name: "cyber-project"

services:
  app:
    build: ../backend/
    image: strapi/app:1.1.0
    container_name: backend-app
    ports:
      - ${APP_PORTS}
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15.5-bullseye
    container_name: postgres-db
    ports:
      - ${DB_PORTS}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - ../database/:/var/lib/postgresql/data

  frontend:
    build: . # Path to your React app directory
    image: cyber/app:1.0.0
    container_name: cyber-app
    ports:
      - "3000:80" # Map React app's port to host
    restart: always
